name: NUnReal
version: ${project.version}
description: Custom command block plugin with ability modifiers
main: com.noloverme.nunreal.NUnReal
api-version: '1.21'
authors:
  - noloverme

permissions:
  nunreal.admin:
    description: Access to NUnReal admin commands
    default: op
  nunreal.craft:
    description: Permission to craft ability blocks
    default: true
  nunreal.spawner.place:
    description: Permission to place ability blocks
    default: true
  nunreal.spawner.break:
    description: Permission to break ability blocks
    default: op
  nunreal.use:
    description: Permission to use ability block menu
    default: true
  nunreal.place:
    description: Permission to place ability blocks
    default: true
  nunreal.break:
    description: Permission to break ability blocks
    default: true

commands:
  nunreal:
    description: Manage NUnReal plugin
    usage: /nunreal <reload|give|givespawner> [player]
    permission: nunreal.admin
